FORMAT: 1A

# IOTインターン

## アラート送信 API [POST /api/v1/alert]

お掃除ロボットに異常が発生したことをLinkitに通知します.

本APIでLinkitに通知するメッセージは以下の通りです.

* #{異常の種類}が発生しました

* Request (application/json)
    * Attributes
        * `type`: `derailment` (enum[string], required) - 異常の種類
            * `dead_battery`: バッテリー不足
            * `derailment`: 脱輪
            * `jamming`: 異物混入

* Response 200 (application/json)
    * Attributes
      * `sent_at`: `2020-01-01T13:00:00Z` (string, required) - Linkitへの送信完了日時 (iso8601形式, UTC)

* Response 400 (application/json)
    * RequestBodyが不正な場合に発生する
    * Attributes
        * `type`: `BadRequest` (string, fixed) - エラー種別
        * `message`: `Unable to understand the request` (string, fixed) - エラーの詳細

* Response 500 (application/json)
    * Linkitへのメッセージの送信に失敗した場合に発生する
    * Attributes
        * `type`: `LinkitError` (string, fixed) - エラー種別
        * `message`: `Error caused on Linkit` (string, fixed) - エラーの詳細
