@startuml SequenceDiagram
title: お掃除ロボットのアラートメッセージ投稿

participant LinkitApp
participant Robot
participant IotInternGear
participant LinkitServer

Robot -> IotInternGear: アラートタイプ (type)
activate IotInternGear

IotInternGear -> IotInternGear: リクエストボディーをバリデーション
alt リクエストボディが不正の場合
  Robot <-- IotInternGear: 400 (BadRequest)
end

IotInternGear -> LinkitServer: メッセージ投稿 (linkit_api_key, notification_user_credential, message)
activate LinkitServer
alt Linkitに通知が成功
  IotInternGear <-- LinkitServer: 成功応答
  Robot <-- IotInternGear: 200 (sent_at)
  LinkitApp <-- LinkitServer: メッセージ通知
else 通知が失敗(認証失敗など)
  IotInternGear <-- LinkitServer: エラー応答
  Robot <-- IotInternGear: 500 (InternalError)
end
deactivate LinkitServer
deactivate IotInternGear
@enduml
