version: "3"

services:
    jupyter:
        build:
            context: .
            dockerfile: Dockerfile
        user: jovyan
        environment:
            CHOWN_HOME: "yes"
            CHOWN_HOME_OPTS: "-R"
            GRANT_SUDO: "yes"
        container_name: elixircise
        ports:
            - "8888:8888"
        volumes:
            - ../.jupyter:/home/jovyan/.jupyter
            - ../notebooks:/home/jovyan/notebooks
